version: '2'
services:
    operasyon-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/operasyon/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=operasyon
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
